"""IDE workflow composite tools for voice-controlled development."""

import logging
from pathlib import Path
from typing import Any, Dict, Optional

from tools.tool_registry import ToolRegistry, ToolMetadata, ToolCategory
from tools.ide_tools.text_editor_bridge import TextEditorBridge

logger = logging.getLogger(__name__)


class IDEWorkflowTool:
    TOOL_METADATA = ToolMetadata(
        name="ide_workflow",
        description="Open IDE, edit files, and run code",
        category=ToolCategory.SYSTEM_TOOLS,
        version="1.1.0",
        author="VoiceOS",
        safety_level="high",
        async_execution=True,
        tags=["ide", "development"],
    )

    def __init__(self, system_integration=None, code_executor=None, text_editor=None, file_manager=None):
        self.system_integration = system_integration
        self.code_executor = code_executor
        self.text_editor = text_editor or TextEditorBridge()
        self.file_manager = file_manager

    async def _generate_content(self, file_path: str, instruction: str) -> str:
        ext = Path(file_path).suffix.lower()
        header = {"py": "#", "js": "//", "ts": "//", "html": "<!--"}.get(ext.lstrip("."), "#")
        stub = f"{header} {instruction}\n{header} Generated by VoiceOS\n"
        try:
            from llm.agent_llm import AgentLLM, ModelConfig, ModelType, LLMRequest
            llm = AgentLLM()
            req = LLMRequest(
                messages=[
                    {"role": "system", "content": "Generate file content only, no markdown fences."},
                    {"role": "user", "content": f"Create content for {file_path}: {instruction}"},
                ],
                model_config=llm.default_config,
            )
            resp = await llm.generate_response(req)
            if resp and resp.content and len(resp.content.strip()) > 10:
                return resp.content.strip()
        except Exception as e:
            logger.debug("LLM content generation unavailable: %s", e)
        return stub

    async def execute(self, method_name: str = "open_project", **kwargs):
        method = method_name or "open_project"
        if method in ("open_project", "open_ide"):
            path = kwargs.get("path") or kwargs.get("target") or kwargs.get("input", "")
            ide = kwargs.get("ide", "vscode")
            if self.system_integration:
                result = await self.system_integration.execute_application_operation(
                    ide, "open", {"args": [path]} if path else {}
                )
                return result
            return {"success": True, "message": f"Open {ide} {path}"}

        if method in ("edit_and_save", "create_file", "create_file_with_content"):
            file_path = kwargs.get("file") or kwargs.get("target") or kwargs.get("path", "")
            content = kwargs.get("content") or kwargs.get("text", "")
            instruction = kwargs.get("instruction") or kwargs.get("input", "")
            if not file_path:
                return {"success": False, "error": "file path required"}
            if method == "create_file_with_content" or (not content and instruction):
                content = await self._generate_content(file_path, instruction or "empty file")
            result = self.text_editor.write(file_path, content)
            if result.get("success") and self.system_integration:
                await self.system_integration.execute_application_operation("vscode", "open", {"args": [file_path]})
            return result

        if method in ("read_file", "read"):
            file_path = kwargs.get("file") or kwargs.get("target") or kwargs.get("path", "")
            return self.text_editor.read(file_path)

        if method in ("run_file", "execute_script"):
            file_path = kwargs.get("file") or kwargs.get("target", "")
            if self.code_executor and file_path:
                code = Path(file_path).read_text(encoding="utf-8")
                return self.code_executor.execute_code(code, language=kwargs.get("language", "python"))
            return {"success": False, "error": "Code executor unavailable"}

        return {"success": False, "error": f"Unknown IDE method: {method}"}


def register_ide_tools(registry: ToolRegistry, system_integration=None) -> None:
    file_manager = None
    code_executor = None
    reg = registry.get_tool("enhanced_file_manager")
    if reg:
        file_manager = reg.instance
    reg = registry.get_tool("code_executor")
    if reg:
        code_executor = reg.instance

    class RegisteredIDEWorkflow(IDEWorkflowTool):
        def __init__(self):
            super().__init__(system_integration, code_executor, TextEditorBridge(), file_manager)

    registry.register_tool(RegisteredIDEWorkflow)

    from tools.ide_tools.text_editor_bridge import register_text_editor_tool
    register_text_editor_tool(registry)
